
osx_image: xcode8.3
language: swift
xcode-project: GradientVC.xcodeproj
xcode_scheme: GradientVC
xcode_sdk: iphonesimulator10.3

script:
- xcodebuild -scheme 'GradientVC' -sdk iphonesimulator CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO test | xcpretty -c
